set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g mouse on 

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Setting up VIM pane / window managment
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Allow resizing splits
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# popup
bind-key -n -N 'Open a scratch session in a popup window' M-3 {
    display-popup -E -w 70% -h 70% 'tmux attach-session -t scratch 2>/dev/null || tmux new-session -s scratch -c "#{pane_current_path}"'
}

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Custom
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "git time cpu-usage ram-usage"
set -g @dracula-show-powerline true
set -g @dracula-show-timezone false

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
